service: ace-attendance-tracker

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    NODE_ENV: ${self:provider.stage}
    SESSION_SECRET: ${env:SESSION_SECRET, 'your-super-secret-key-change-in-production'}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
    timeout: 29
    memorySize: 512

package:
  include:
    - handler.cjs
    - server/*.cjs
